"""`vogon index`: write the index of every record, generated from the
frontmatter, to `<records>/out/index.md` (REQ-REC-6).

The index lists each record file once with its id, title, status and modules.
It is sorted by type, module and number and carries no timestamp, so running
it again with no change to the records writes the same bytes.
"""

from __future__ import annotations

import sys
from pathlib import Path

import ids
import records
from checks import rel
from config import Config
from findings import Finding, failure

NAME = "index"
HELP = "Write the record index to out/index.md from the record frontmatter."

OUT_DIR = "out"
FILENAME = "index.md"
TYPE_ORDER = {p: n for n, p in enumerate(ids.PREFIXES)}  # REQ, FACT, CON, DEC


def add_arguments(parser) -> None:
    pass


def index_path(records_dir: Path) -> Path:
    return Path(records_dir) / OUT_DIR / FILENAME


def _cell(value) -> str:
    text = "" if value is None else str(value)
    return " ".join(text.split()).replace("|", "\\|")


def _status(r: records.Record) -> str:
    if r.status == "superseded_by":
        return f"superseded_by {r.superseded_by}"
    return r.status or ""


def _order(r: records.Record):
    rid = r.parsed_id
    if rid is None:
        return (len(TYPE_ORDER), "", 0, r.path.name)
    return (TYPE_ORDER.get(rid.prefix, len(TYPE_ORDER)), rid.module or "", rid.value, r.path.name)


def render(found: list[records.Record]) -> str:
    lines = [
        "# Record index",
        "",
        "Generated by `vogon index` from the record frontmatter. Do not edit.",
        "",
        "| Id | Title | Status | Modules |",
        "| --- | --- | --- | --- |",
    ]
    for r in sorted(found, key=_order):
        title = r.meta.get("title")
        lines.append(f"| {_cell(r.id)} | {_cell(title)} | {_cell(_status(r))} | "
                     f"{_cell(', '.join(r.modules))} |")
    return "\n".join(lines) + "\n"


def run(args, config: Config) -> list[Finding]:
    found, errors = records.load_all(config.records_dir)
    findings = [failure(f"record {e.message}; it is not in the index", path=rel(config, e.path),
                        line=e.line, requirement="REQ-REC-6") for e in errors]
    path = index_path(config.records_dir)
    text = render(found)
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.is_file() or path.read_text(encoding="utf-8") != text:
        path.write_text(text, encoding="utf-8")
    sys.stdout.write(f"{rel(config, path)}\n")
    return findings
